/*html hbs*/ 
import './index.hbs';
/*styles files*/ 
import './scss/fonts.css';
import './scss/normalize.css';
import './scss/base.css';
import './scss/header.css';
import './scss/ymap.css';
import './scss/slider.css';
import './scss/scroll.css';
/*img files*/ 
import './img/sprite.svg';
import './img/red-marker.png';
/*js files*/ 
import './js/geoReviews.js';
